name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Run Tests
      run: pytest

    - name: Build Docker Image
      run: docker build -t flask-cicd-demo -f ./Dockerfile .

    - name: Security Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'flask-cicd-demo'
        format: 'table'
        exit-code: '0'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker tag flask-cicd-demo ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "✅ Connected to EC2 successfully"
          whoami
          uname -a
          docker --version || echo "⚠️ Docker not installed on EC2"

    - name: Deploy to EC2 (Staging)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "🚀 Starting deployment on EC2..."

          # Docker login (required for private images)
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          echo "🔽 Pulling latest Docker image..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest

          echo "🛑 Stopping old container (if exists)..."
          docker stop flask-cicd || true

          echo "🗑️ Removing old container (if exists)..."
          docker rm flask-cicd || true

          echo "▶️ Running new container..."
          docker run -d -p 80:5000 --restart unless-stopped --name flask-cicd \
            -v /mnt/data:/app/data \
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest

          echo "✅ Deployment finished successfully!"

    
        # - name: Deploy to EC2 (Staging)
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ubuntu
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     script: |
    #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest
    #       docker stop flask-cicd || true
    #       docker rm flask-cicd || true
    #       docker run -d -p 5000:5000 --name flask-cicd ${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo:latest
    
    - name: Slack Notification
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "🚨 CI/CD Pipeline failed for ${{ github.repository }} on ${{ github.ref }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
